include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - file_names
    - exhaustive_cases
    # New roles
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - avoid_print # we should use Fimber

analyzer:
  errors:
    todo: warning
    unused_import: error
    unnecessary_import: error
    unnecessary_getters_setters: error
    missing_required_param: error
    file_names: error
    camel_case_types: error
    missing_return: error
    exhaustive_cases: error

    prefer_final_locals: error
    prefer_typing_uninitialized_variables: error
    prefer_function_declarations_over_variables: false

    avoid_function_literals_in_foreach_calls: false
    avoid_redundant_argument_values: false
    avoid_positional_boolean_parameters: false
    sort_pub_dependencies: false
    unused_local_variable: error
    unused_field: error
    sort_child_properties_last: error
    unnecessary_non_null_assertion: error
    invalid_use_of_visible_for_testing_member: error
    unrelated_type_equality_checks: error
    unnecessary_null_comparison: error
    dead_null_aware_expression: error
    avoid_returning_null_for_void: error