name: find_coffee_app
description: This is an application that shows information about coffee stores in your zone, built with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: 3.1.3
  flutter: 3.13.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  flutter_fimber: 0.7.1
  google_maps_flutter: 2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.3

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 500
        - asset: assets/fonts/Lato-Light.ttf
          weight: 400