name: find_coffee_app
description: This is an application that shows information about coffee stores in your zone, built with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: 3.1.3
  flutter: 3.13.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  flutter_fimber: 0.7.1
  google_maps_flutter: 2.5.0
  flutter_config: 2.0.2
  intl: 0.18.1
  ui_theme:
    path: packages/ui_theme
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.3
  intl_utils: 2.8.5

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: en
  class_name: I18n
  enabled: true