name: ui_theme
description: A UI theme.
version: 0.0.1
homepage: ""

environment:
  sdk: 3.1.3
  flutter: 3.13.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 500
        - asset: assets/fonts/Lato-Light.ttf
          weight: 400